good_morningdlg = [
    "Rise and shine, sir! A brand-new day of possibilities.",
    "Good morning, sir! Time to own the day like a true champion.",
    "Greetings, sir! The world awaits your brilliance.",
    "Hello, sir! A fresh start to make today extraordinary.",
    "Wake up, sir! Your journey of greatness begins now.",
    "Embrace the morning, sir! Another chance to shine.",
    "A warm good morning, sir! The world is yours to conquer.",
    "Rise with the sun, sir! Success awaits you.",
    "Good morning, sir! Make today as amazing as you are.",
    "New day, new opportunities, sir! Let's make it count.",
    "Wake up, sir! Another step toward greatness starts now.",
    "Good morning, sir! The universe is on your side today.",
    "Hello, sir! Brighten the world with your presence.",
    "Rise, sir! A magnificent day is calling you.",
    "Top of the morning, sir! Make the most of it.",
    "Sun’s up, sir! Your journey of excellence continues.",
    "Step into greatness, sir! The day is yours to command.",
    "Morning, sir! Success is knocking on your door.",
    "Wake up and conquer, sir! The world is watching.",
    "Good morning, sir! Seize every golden moment.",
    "The sun salutes you, sir! Own the day.",
    "Time to shine, sir! Your brilliance lights up the day.",
    "Rise and grind, sir! Another chance to make history.",
    "A fresh day, a fresh mindset, sir! Let’s go!",
    "Morning motivation: You’re unstoppable, sir!",
    "Good morning, sir! Your energy fuels greatness.",
    "Wake up, sir! A legendary day begins now.",
    "Sir, the world awaits your magic! Good morning.",
    "Embrace the sunrise, sir! Great things are ahead.",
    "Rise, sir! Another opportunity to excel is here.",
    "Sir, today is your canvas—paint it with success!",
    "Wake up, sir! The world needs your spark.",
    "A magnificent morning to you, sir! Let's achieve.",
    "Sunrise signals success, sir! Go grab it.",
    "Be unstoppable today, sir! Good morning.",
    "Hello, sir! Your brilliance is a gift to this world.",
    "Another sunrise, another chance, sir! Make it count.",
    "Rise, sir! Time to make an impact.",
    "Morning, sir! You are destined for greatness.",
    "New dawn, new goals, sir! Let’s crush them.",
    "Today is special, sir! Because you're in it.",
    "Wake up, sir! Your legacy awaits your actions.",
    "A golden morning to you, sir! Time to shine.",
    "Rise and be phenomenal, sir! Good morning.",
    "Sir, start today with passion and end with triumph.",
    "Seize the moment, sir! Greatness is calling.",
    "The world is yours to inspire, sir! Good morning.",
    "Hello, sir! Your presence makes today better.",
    "Start strong, sir! Today is another victory waiting.",
    "Sir, make today your masterpiece! Good morning.",
    "Every morning is a fresh blessing, sir!",
    "Shine brighter than the sun today, sir!",
    "Make today count, sir! Your journey is inspiring.",
    "Rise, sir! Time to build your empire.",
    "Morning, sir! Success starts with the first step.",
    "Unlock new achievements today, sir! Good morning.",
    "Embrace the grind, sir! Today is yours.",
    "You are limitless, sir! Rise and shine.",
    "Good morning, sir! Set the world on fire with your passion.",
    "Sir, awaken your inner greatness! Today is yours.",
    "Hello, sir! The world is a better place with you in it.",
    "Your time is now, sir! Rise and shine.",
    "Morning, sir! You’re made for remarkable things.",
    "Let your dreams guide you today, sir!",
    "Sir, good morning! The stage is set for your success.",
    "Rise, sir! Chase excellence with every breath.",
    "Make every second today worthwhile, sir!",
    "A phenomenal morning to a phenomenal sir!",
    "Sir, today is another page in your success story.",
    "Wake up and be legendary, sir!",
    "The morning whispers success, sir! Listen to it.",
    "Sir, the sunrise brings new opportunities!",
    "New day, new energy, sir! Let’s go all in.",
    "Sir, your greatness shines brighter than the sun.",
    "Keep moving forward, sir! Today holds wonders.",
    "Sir, good morning! Step into greatness.",
    "Each morning is a gift, sir! Open it wisely.",
    "Make waves today, sir! You were born for this.",
    "Conquer the morning, sir! Success will follow.",
    "Today is a powerhouse of potential, sir!",
    "Another day, another win, sir! Go for it.",
    "Rise, sir! Be the legend you were meant to be.",
    "Own the morning, sir! The day is yours.",
    "Sir, your success starts with this very moment.",
    "Step into excellence, sir! Good morning.",
    "The sun rises for you, sir! Make it worthwhile.",
    "A bright morning to a bright sir!",
    "Your energy defines today, sir! Shine brightly.",
    "Good vibes, good goals, sir! Let’s crush it.",
    "Wake up, sir! Your potential is limitless.",
    "Sir, let’s turn dreams into reality today!",
    "Each sunrise brings fresh hope, sir!",
    "You are the architect of today, sir! Design it well.",
    "Morning has arrived, sir! Let’s make history.",
    "Sir, your determination is the key to today’s success.",
    "Good morning, sir! Let’s light up the world.",
    "Rise, sir! Excellence is your second nature."
]

sentences = [
    "Hello I am Lucky. How can I help you?",
    "Greetings Lucky here. What can I do for you?",
    "Hi there I’m Lucky. How can I be of assistance?",
    "Hello it’s Lucky. How may I assist you today?",
    "Hey I’m Lucky. How can I help you out?",
    "Greetings I am Lucky. How can I serve you?",
    "Hello I am Lucky. What can I do for you today?",
    "Hi Lucky at your service. How can I assist you?",
    "Hey Lucky here. How may I help you?",
    "Hello I am Lucky. What do you need help with?",
    "Greetings from Lucky . How can I assist you today?",
    "Hi Lucky is here to help. How can I assist?",
    "Hello I am Lucky. How can I serve your needs?",
    "Hi there I’m Lucky. Let me know how I can assist.",
    "Hey Lucky at your service. How can I help you today?",
    "Greetings Lucky here. What can I do for you today?",
    "Hello, it’s Lucky. How can I make your day easier?",
    "Hi . Lucky here, ready to help. What do you need?",
    "Hello, I’m Lucky. How may I assist you today?",
    "Greetings from Lucky . How can I be of service?",
    "Hey there . I’m Lucky. What can I do for you?",
    "Hi, I’m Lucky. How can I be helpful today?",
    "Hello, I’m Lucky. Let me know how I can help you out.",
    "Hey . It’s Lucky. What can I do for you today?",
    "Hello . I’m Lucky. How can I assist you right now?",
    "Hi . Lucky here. How may I help you with something?",
    "Hello, I’m Lucky. How can I support you today?",
    "Greetings from Lucky . How can I assist you today?",
    "Hey . Lucky at your service. What can I do for you?",
    "Hello, I’m Lucky. How can I make things easier for you?",
    "Hi there . I’m Lucky. How may I help you today?",
    "Hello . Lucky here. How can I assist you with something?",
    "Greetings . I’m Lucky. How can I support you today?",
    "Hi . Lucky at your service. How can I help you?",
    "Hello, I’m Lucky. What can I do to assist you today?",
    "Hi . Lucky here. How can I be of help today?",
    "Hey, I’m Lucky. What can I help you with?",
    "Hello, it’s Lucky. How can I help you with that?",
    "Greetings from Lucky . How can I help today?",
    "Hi . Lucky here. What do you need help with today?",
    "Hello, I’m Lucky. How can I assist you right now?",
    "Hey . Lucky here. How can I be of help?",
    "Hi there . I’m Lucky. How can I serve you?",
    "Hello, I’m Lucky. How can I assist you today?",
    "Hi . Lucky here. What can I do to make things easier?",
    "Hello, it’s Lucky. How can I be of service to you?",
    "Hey . Lucky here. How can I assist you right away?",
    "Greetings from Lucky . How can I help you today?",
    "Hello, I’m Lucky. What would you like help with?",
    "Hi . Lucky here. What assistance do you need?",
    "Hey . It’s Lucky. How may I help today?",
    "Hello, I’m Lucky. How can I help you out today?",
    "Greetings from Lucky . How can I assist?",
    "Hi there . I’m Lucky. How can I help you today?",
    "Hey . Lucky at your service. What can I do for you today?",
    "Hello, I’m Lucky. What can I do to help you?",
    "Hi . Lucky here. How can I make things easier for you?",
    "Hello . Lucky here, at your service. How can I assist?",
    "Hey . I’m Lucky. How can I assist you right now?",
    "Hi there . I’m Lucky. How may I help you today?",
    "Hello, it’s Lucky. How can I support you today?",
    "Greetings from Lucky . What can I do for you today?",
    "Hi . Lucky here. What do you need help with today?",
    "Hello, I’m Lucky. How may I assist you with this?",
    "Hey . Lucky here. How can I help you today?",
    "Greetings from Lucky . How can I make things easier?",
    "Hi . Lucky here, ready to assist. How can I help?",
    "Hello . I’m Lucky. How can I help you right now?",
    "Hey . Lucky at your service. How may I help you today?",
    "Hi, I’m Lucky. How can I assist you today?",
    "Greetings from Lucky . How can I be of help?",
    "Hello . Lucky here. How may I assist with your needs?",
    "Hey, it’s Lucky. How can I serve you today?",
    "Hi there . Lucky here, ready to assist. What do you need?",
    "Hello, I’m Lucky. How can I assist you right away?",
    "Greetings . Lucky here. How can I help you today?",
    "Hi, I’m Lucky. What can I do for you right now?",
    "Hello, I’m Lucky. How can I help you today?",
    "Hi . Lucky at your service. How may I help you?",
    "Hey . Lucky here. How can I help you today?",
    "Greetings from Lucky . How can I assist you right now?",
    "Hello, I’m Lucky. What do you need assistance with?",
    "Hi . Lucky at your service. How can I assist?",
    "Hey, I’m Lucky. How can I help you today?",
    "Greetings from Lucky . What can I assist you with?",
    "Hello . Lucky here. How can I support you?",
    "Hi . Lucky here. How can I help you out?",
    "Greetings . I’m Lucky. How can I assist you?",
    "Hi . Lucky here. What can I help with today?",
    "Hello, it’s Lucky. How may I assist you today?",
    "Hey . Lucky here. How can I help you out?",
    "Hi, I’m Lucky. How can I assist you with this?",
    "Greetings from Lucky . How can I assist you today?",
    "Hello, it’s Lucky. What can I help you with?",
    "Hi . Lucky at your service. How can I help?",
    "Hey . It’s Lucky. How may I assist you?",
    "Greetings from Lucky . What can I do for you?",
    "Hello, I’m Lucky. How can I make things easier for you?",
    "Hi there . Lucky here. What do you need help with?",
    "Hey . Lucky here. How can I assist?",
    "Greetings from Lucky . What can I do for you?",
    "Hi . Lucky here. How may I assist today?",
    "Hello, I’m Lucky. How can I assist you right away?",
    "Hey . Lucky at your service. How can I help?",
    "Greetings from Lucky . How can I assist you right now?",
    "Hi . Lucky here. How can I make things easier?",
    "Hello, I’m Lucky. How can I assist you right now?",
    "Greetings . Lucky here. What can I do for you?",
    "Hi . Lucky here. How can I assist you with this?",
    "Hey . Lucky here. What do you need help with today?",
    "Hello, I’m Lucky. How can I assist you right away?",
    "Hi there . Lucky here. How can I help you out today?",
    "Greetings from Lucky . How may I assist you?",
    "Hello . I’m Lucky. How can I assist you today?",
    "Hey . Lucky here. What do you need help with?",
    "Hi there . Lucky here, how may I assist you today?",
    "Hello, I’m Lucky. How can I be of service?",
    "Hey . Lucky here. How can I assist you today?",
    "Hello, it’s Lucky. How may I help you?",
    "Hi . Lucky here. How can I assist today?",
    "Hello . Lucky at your service. How can I assist?",
    "Greetings . Lucky here. How may I help you today?",
    "Hi . Lucky here, how can I assist you with that?"
]



websites = {
    'google': 'https://www.google.com',
    'youtube': 'https://www.youtube.com',
    'facebook': 'https://www.facebook.com',
    'twitter': 'https://www.twitter.com',
    'instagram': 'https://www.instagram.com',
    'linkedin': 'https://www.linkedin.com',
    'reddit': 'https://www.reddit.com',
    'tiktok': 'https://www.tiktok.com',
    'whatsapp': 'https://www.whatsapp.com',
    'snapchat': 'https://www.snapchat.com',
    'netflix': 'https://www.netflix.com',
    'amazon': 'https://www.amazon.com',
    'flipkart': 'https://www.flipkart.com',
    'apple': 'https://www.apple.com',
    'microsoft': 'https://www.microsoft.com',
    'yahoo': 'https://www.yahoo.com',
    'bing': 'https://www.bing.com',
    'paypal': 'https://www.paypal.com',
    'ebay': 'https://www.ebay.com',
    'walmart': 'https://www.walmart.com',
    'target': 'https://www.target.com',
    'craigslist': 'https://www.craigslist.org',
    'pinterest': 'https://www.pinterest.com',
    'quora': 'https://www.quora.com',
    'medium': 'https://www.medium.com',
    'spotify': 'https://www.spotify.com',
    'soundcloud': 'https://www.soundcloud.com',
    'zoom': 'https://www.zoom.us',
    'skype': 'https://www.skype.com',
    'github': 'https://www.github.com',
    'gitlab': 'https://www.gitlab.com',
    'stackoverflow': 'https://www.stackoverflow.com',
    'bitbucket': 'https://www.bitbucket.org',
    'udemy': 'https://www.udemy.com',
    'coursera': 'https://www.coursera.org',
    'khanacademy': 'https://www.khanacademy.org',
    'edx': 'https://www.edx.org',
    'udacity': 'https://www.udacity.com',
    'bbc': 'https://www.bbc.com',
    'cnn': 'https://www.cnn.com',
    'nytimes': 'https://www.nytimes.com',
    'theguardian': 'https://www.theguardian.com',
    'forbes': 'https://www.forbes.com',
    'bloomberg': 'https://www.bloomberg.com',
    'reuters': 'https://www.reuters.com',
    'espn': 'https://www.espn.com',
    'goal': 'https://www.goal.com',
    'fifa': 'https://www.fifa.com',
    'nba': 'https://www.nba.com',
    'nfl': 'https://www.nfl.com',
    'icc': 'https://www.icc-cricket.com',
    'cricbuzz': 'https://www.cricbuzz.com',
    'hotstar': 'https://www.hotstar.com',
    'primevideo': 'https://www.primevideo.com',
    'disneyplus': 'https://www.disneyplus.com',
    'hulu': 'https://www.hulu.com',
    'hbo': 'https://www.hbo.com',
    'deezer': 'https://www.deezer.com',
    'twitch': 'https://www.twitch.tv',
    'kick': 'https://www.kick.com',
    'discord': 'https://www.discord.com',
    'telegram': 'https://www.telegram.org',
    'weibo': 'https://www.weibo.com',
    'wechat': 'https://www.wechat.com',
    'baidu': 'https://www.baidu.com',
    'duckduckgo': 'https://www.duckduckgo.com',
    'yandex': 'https://www.yandex.com',
    'medium': 'https://www.medium.com',
    'theverge': 'https://www.theverge.com',
    'engadget': 'https://www.engadget.com',
    'gsmarena': 'https://www.gsmarena.com',
    'techcrunch': 'https://www.techcrunch.com',
    'androidauthority': 'https://www.androidauthority.com',
    'xda-developers': 'https://www.xda-developers.com',
    'cnet': 'https://www.cnet.com',
    'tomshardware': 'https://www.tomshardware.com',
    'cloudflare': 'https://www.cloudflare.com',
    'oracle': 'https://www.oracle.com',
    'adobe': 'https://www.adobe.com',
    'canva': 'https://www.canva.com',
    'pixabay': 'https://www.pixabay.com',
    'pexels': 'https://www.pexels.com',
    'unsplash': 'https://www.unsplash.com',
    'flickr': 'https://www.flickr.com',
    'opensea': 'https://www.opensea.io',
    'coinmarketcap': 'https://www.coinmarketcap.com',
    'coingecko': 'https://www.coingecko.com',
    'binance': 'https://www.binance.com',
    'coinbase': 'https://www.coinbase.com',
    'robinhood': 'https://www.robinhood.com',
    'tradingview': 'https://www.tradingview.com',
    'fiverr': 'https://www.fiverr.com',
    'upwork': 'https://www.upwork.com',
    'freelancer': 'https://www.freelancer.com',
    'toptal': 'https://www.toptal.com',
    'indeed': 'https://www.indeed.com',
    'glassdoor': 'https://www.glassdoor.com',
    'monster': 'https://www.monster.com',
    'naukri': 'https://www.naukri.com',
    'timesjobs': 'https://www.timesjobs.com',
    'shutterstock': 'https://www.shutterstock.com',
    'istockphoto': 'https://www.istockphoto.com',
    'pexels': 'https://www.pexels.com',
    'git': 'https://www.git-scm.com',
    'npm': 'https://www.npmjs.com',
    'pypi': 'https://www.pypi.org',
    'r-project': 'https://www.r-project.org',
    'docker': 'https://www.docker.com',
    'kubernetes': 'https://www.kubernetes.io',
    'tensorflow': 'https://www.tensorflow.org',
    'pytorch': 'https://www.pytorch.org',
    'opencv': 'https://www.opencv.org',
    'wikipedia': 'https://www.wikipedia.org',
    'wikihow': 'https://www.wikihow.com',
    'wikimedia': 'https://www.wikimedia.org',
    'archive': 'https://www.archive.org',
    'gutenberg': 'https://www.gutenberg.org',
    'medium': 'https://www.medium.com',
    'theconversation': 'https://www.theconversation.com',
    'nasa': 'https://www.nasa.gov',
    'esa': 'https://www.esa.int',
    'who': 'https://www.who.int',
    'cdc': 'https://www.cdc.gov',
    'mayo': 'https://www.mayoclinic.org',
    'nih': 'https://www.nih.gov',
    'un': 'https://www.un.org',
    'whitehouse': 'https://www.whitehouse.gov'
}
